-- ========================================
-- NovaLedger Seed Data
-- Flyway Migration V13
-- CATEGORIES：為每位測試租戶建立預設收支分類
--
-- 結構：
--   頂層分類 (PARENT_ID = NULL)
--   └── 子分類 (PARENT_ID = 頂層 ID)
-- ========================================

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ========================================
-- Alice 的租戶分類
-- ========================================

-- ---- 收入頂層 ----
INSERT INTO categories (TENANT_ID, PARENT_ID, NAME, TYPE, ICON_NAME, COLOR_HEX, IS_SYSTEM_DEFAULT, SOURCE_TEMPLATE_ID, SORT_ORDER, IS_ACTIVE, CREATED_AT, UPDATED_AT)
SELECT T.ID, NULL, '薪資收入', 'INCOME', 'wallet',       '#4CAF50', TRUE, NULL, 1,  TRUE, NOW(), NOW() FROM tenants T WHERE T.CODE = 'alice-personal';
INSERT INTO categories (TENANT_ID, PARENT_ID, NAME, TYPE, ICON_NAME, COLOR_HEX, IS_SYSTEM_DEFAULT, SOURCE_TEMPLATE_ID, SORT_ORDER, IS_ACTIVE, CREATED_AT, UPDATED_AT)
SELECT T.ID, NULL, '投資收益', 'INCOME', 'trending-up',  '#2196F3', TRUE, NULL, 2,  TRUE, NOW(), NOW() FROM tenants T WHERE T.CODE = 'alice-personal';
INSERT INTO categories (TENANT_ID, PARENT_ID, NAME, TYPE, ICON_NAME, COLOR_HEX, IS_SYSTEM_DEFAULT, SOURCE_TEMPLATE_ID, SORT_ORDER, IS_ACTIVE, CREATED_AT, UPDATED_AT)
SELECT T.ID, NULL, '其他收入', 'INCOME', 'plus-circle',  '#9C27B0', TRUE, NULL, 3,  TRUE, NOW(), NOW() FROM tenants T WHERE T.CODE = 'alice-personal';

-- ---- 收入子分類 ----
INSERT INTO categories (TENANT_ID, PARENT_ID, NAME, TYPE, ICON_NAME, COLOR_HEX, IS_SYSTEM_DEFAULT, SOURCE_TEMPLATE_ID, SORT_ORDER, IS_ACTIVE, CREATED_AT, UPDATED_AT)
SELECT T.ID, C.ID, '月薪', 'INCOME', NULL, NULL, TRUE, NULL, 1, TRUE, NOW(), NOW()
FROM tenants T JOIN categories C ON C.TENANT_ID = T.ID AND C.NAME = '薪資收入' AND C.TYPE = 'INCOME'
WHERE T.CODE = 'alice-personal';
INSERT INTO categories (TENANT_ID, PARENT_ID, NAME, TYPE, ICON_NAME, COLOR_HEX, IS_SYSTEM_DEFAULT, SOURCE_TEMPLATE_ID, SORT_ORDER, IS_ACTIVE, CREATED_AT, UPDATED_AT)
SELECT T.ID, C.ID, '獎金', 'INCOME', NULL, NULL, TRUE, NULL, 2, TRUE, NOW(), NOW()
FROM tenants T JOIN categories C ON C.TENANT_ID = T.ID AND C.NAME = '薪資收入' AND C.TYPE = 'INCOME'
WHERE T.CODE = 'alice-personal';
INSERT INTO categories (TENANT_ID, PARENT_ID, NAME, TYPE, ICON_NAME, COLOR_HEX, IS_SYSTEM_DEFAULT, SOURCE_TEMPLATE_ID, SORT_ORDER, IS_ACTIVE, CREATED_AT, UPDATED_AT)
SELECT T.ID, C.ID, '股利', 'INCOME', NULL, NULL, TRUE, NULL, 1, TRUE, NOW(), NOW()
FROM tenants T JOIN categories C ON C.TENANT_ID = T.ID AND C.NAME = '投資收益' AND C.TYPE = 'INCOME'
WHERE T.CODE = 'alice-personal';

-- ---- 支出頂層 ----
INSERT INTO categories (TENANT_ID, PARENT_ID, NAME, TYPE, ICON_NAME, COLOR_HEX, IS_SYSTEM_DEFAULT, SOURCE_TEMPLATE_ID, SORT_ORDER, IS_ACTIVE, CREATED_AT, UPDATED_AT)
SELECT T.ID, NULL, '飲食',     'EXPENSE', 'restaurant',   '#F44336', TRUE, NULL, 1,  TRUE, NOW(), NOW() FROM tenants T WHERE T.CODE = 'alice-personal';
INSERT INTO categories (TENANT_ID, PARENT_ID, NAME, TYPE, ICON_NAME, COLOR_HEX, IS_SYSTEM_DEFAULT, SOURCE_TEMPLATE_ID, SORT_ORDER, IS_ACTIVE, CREATED_AT, UPDATED_AT)
SELECT T.ID, NULL, '交通',     'EXPENSE', 'car',          '#FF9800', TRUE, NULL, 2,  TRUE, NOW(), NOW() FROM tenants T WHERE T.CODE = 'alice-personal';
INSERT INTO categories (TENANT_ID, PARENT_ID, NAME, TYPE, ICON_NAME, COLOR_HEX, IS_SYSTEM_DEFAULT, SOURCE_TEMPLATE_ID, SORT_ORDER, IS_ACTIVE, CREATED_AT, UPDATED_AT)
SELECT T.ID, NULL, '居家生活', 'EXPENSE', 'home',         '#795548', TRUE, NULL, 3,  TRUE, NOW(), NOW() FROM tenants T WHERE T.CODE = 'alice-personal';
INSERT INTO categories (TENANT_ID, PARENT_ID, NAME, TYPE, ICON_NAME, COLOR_HEX, IS_SYSTEM_DEFAULT, SOURCE_TEMPLATE_ID, SORT_ORDER, IS_ACTIVE, CREATED_AT, UPDATED_AT)
SELECT T.ID, NULL, '娛樂',     'EXPENSE', 'game-pad',     '#E91E63', TRUE, NULL, 4,  TRUE, NOW(), NOW() FROM tenants T WHERE T.CODE = 'alice-personal';
INSERT INTO categories (TENANT_ID, PARENT_ID, NAME, TYPE, ICON_NAME, COLOR_HEX, IS_SYSTEM_DEFAULT, SOURCE_TEMPLATE_ID, SORT_ORDER, IS_ACTIVE, CREATED_AT, UPDATED_AT)
SELECT T.ID, NULL, '醫療健康', 'EXPENSE', 'health',       '#00BCD4', TRUE, NULL, 5,  TRUE, NOW(), NOW() FROM tenants T WHERE T.CODE = 'alice-personal';
INSERT INTO categories (TENANT_ID, PARENT_ID, NAME, TYPE, ICON_NAME, COLOR_HEX, IS_SYSTEM_DEFAULT, SOURCE_TEMPLATE_ID, SORT_ORDER, IS_ACTIVE, CREATED_AT, UPDATED_AT)
SELECT T.ID, NULL, '其他支出', 'EXPENSE', 'more-horiz',   '#9E9E9E', TRUE, NULL, 99, TRUE, NOW(), NOW() FROM tenants T WHERE T.CODE = 'alice-personal';

-- ---- 支出子分類 ----
INSERT INTO categories (TENANT_ID, PARENT_ID, NAME, TYPE, ICON_NAME, COLOR_HEX, IS_SYSTEM_DEFAULT, SOURCE_TEMPLATE_ID, SORT_ORDER, IS_ACTIVE, CREATED_AT, UPDATED_AT)
SELECT T.ID, C.ID, '早餐', 'EXPENSE', NULL, NULL, TRUE, NULL, 1, TRUE, NOW(), NOW()
FROM tenants T JOIN categories C ON C.TENANT_ID = T.ID AND C.NAME = '飲食' AND C.TYPE = 'EXPENSE'
WHERE T.CODE = 'alice-personal';
INSERT INTO categories (TENANT_ID, PARENT_ID, NAME, TYPE, ICON_NAME, COLOR_HEX, IS_SYSTEM_DEFAULT, SOURCE_TEMPLATE_ID, SORT_ORDER, IS_ACTIVE, CREATED_AT, UPDATED_AT)
SELECT T.ID, C.ID, '午餐', 'EXPENSE', NULL, NULL, TRUE, NULL, 2, TRUE, NOW(), NOW()
FROM tenants T JOIN categories C ON C.TENANT_ID = T.ID AND C.NAME = '飲食' AND C.TYPE = 'EXPENSE'
WHERE T.CODE = 'alice-personal';
INSERT INTO categories (TENANT_ID, PARENT_ID, NAME, TYPE, ICON_NAME, COLOR_HEX, IS_SYSTEM_DEFAULT, SOURCE_TEMPLATE_ID, SORT_ORDER, IS_ACTIVE, CREATED_AT, UPDATED_AT)
SELECT T.ID, C.ID, '晚餐', 'EXPENSE', NULL, NULL, TRUE, NULL, 3, TRUE, NOW(), NOW()
FROM tenants T JOIN categories C ON C.TENANT_ID = T.ID AND C.NAME = '飲食' AND C.TYPE = 'EXPENSE'
WHERE T.CODE = 'alice-personal';
INSERT INTO categories (TENANT_ID, PARENT_ID, NAME, TYPE, ICON_NAME, COLOR_HEX, IS_SYSTEM_DEFAULT, SOURCE_TEMPLATE_ID, SORT_ORDER, IS_ACTIVE, CREATED_AT, UPDATED_AT)
SELECT T.ID, C.ID, '飲料', 'EXPENSE', NULL, NULL, TRUE, NULL, 4, TRUE, NOW(), NOW()
FROM tenants T JOIN categories C ON C.TENANT_ID = T.ID AND C.NAME = '飲食' AND C.TYPE = 'EXPENSE'
WHERE T.CODE = 'alice-personal';
INSERT INTO categories (TENANT_ID, PARENT_ID, NAME, TYPE, ICON_NAME, COLOR_HEX, IS_SYSTEM_DEFAULT, SOURCE_TEMPLATE_ID, SORT_ORDER, IS_ACTIVE, CREATED_AT, UPDATED_AT)
SELECT T.ID, C.ID, '捷運/公車', 'EXPENSE', NULL, NULL, TRUE, NULL, 1, TRUE, NOW(), NOW()
FROM tenants T JOIN categories C ON C.TENANT_ID = T.ID AND C.NAME = '交通' AND C.TYPE = 'EXPENSE'
WHERE T.CODE = 'alice-personal';
INSERT INTO categories (TENANT_ID, PARENT_ID, NAME, TYPE, ICON_NAME, COLOR_HEX, IS_SYSTEM_DEFAULT, SOURCE_TEMPLATE_ID, SORT_ORDER, IS_ACTIVE, CREATED_AT, UPDATED_AT)
SELECT T.ID, C.ID, '計程車/Uber', 'EXPENSE', NULL, NULL, TRUE, NULL, 2, TRUE, NOW(), NOW()
FROM tenants T JOIN categories C ON C.TENANT_ID = T.ID AND C.NAME = '交通' AND C.TYPE = 'EXPENSE'
WHERE T.CODE = 'alice-personal';
INSERT INTO categories (TENANT_ID, PARENT_ID, NAME, TYPE, ICON_NAME, COLOR_HEX, IS_SYSTEM_DEFAULT, SOURCE_TEMPLATE_ID, SORT_ORDER, IS_ACTIVE, CREATED_AT, UPDATED_AT)
SELECT T.ID, C.ID, '房租', 'EXPENSE', NULL, NULL, TRUE, NULL, 1, TRUE, NOW(), NOW()
FROM tenants T JOIN categories C ON C.TENANT_ID = T.ID AND C.NAME = '居家生活' AND C.TYPE = 'EXPENSE'
WHERE T.CODE = 'alice-personal';
INSERT INTO categories (TENANT_ID, PARENT_ID, NAME, TYPE, ICON_NAME, COLOR_HEX, IS_SYSTEM_DEFAULT, SOURCE_TEMPLATE_ID, SORT_ORDER, IS_ACTIVE, CREATED_AT, UPDATED_AT)
SELECT T.ID, C.ID, '水電費', 'EXPENSE', NULL, NULL, TRUE, NULL, 2, TRUE, NOW(), NOW()
FROM tenants T JOIN categories C ON C.TENANT_ID = T.ID AND C.NAME = '居家生活' AND C.TYPE = 'EXPENSE'
WHERE T.CODE = 'alice-personal';

-- ========================================
-- Bob 的租戶分類（與 Alice 相同模板）
-- ========================================

-- ---- 收入頂層 ----
INSERT INTO categories (TENANT_ID, PARENT_ID, NAME, TYPE, ICON_NAME, COLOR_HEX, IS_SYSTEM_DEFAULT, SOURCE_TEMPLATE_ID, SORT_ORDER, IS_ACTIVE, CREATED_AT, UPDATED_AT)
SELECT T.ID, NULL, '薪資收入', 'INCOME', 'wallet',       '#4CAF50', TRUE, NULL, 1,  TRUE, NOW(), NOW() FROM tenants T WHERE T.CODE = 'bob-personal';
INSERT INTO categories (TENANT_ID, PARENT_ID, NAME, TYPE, ICON_NAME, COLOR_HEX, IS_SYSTEM_DEFAULT, SOURCE_TEMPLATE_ID, SORT_ORDER, IS_ACTIVE, CREATED_AT, UPDATED_AT)
SELECT T.ID, NULL, '投資收益', 'INCOME', 'trending-up',  '#2196F3', TRUE, NULL, 2,  TRUE, NOW(), NOW() FROM tenants T WHERE T.CODE = 'bob-personal';
INSERT INTO categories (TENANT_ID, PARENT_ID, NAME, TYPE, ICON_NAME, COLOR_HEX, IS_SYSTEM_DEFAULT, SOURCE_TEMPLATE_ID, SORT_ORDER, IS_ACTIVE, CREATED_AT, UPDATED_AT)
SELECT T.ID, NULL, '其他收入', 'INCOME', 'plus-circle',  '#9C27B0', TRUE, NULL, 3,  TRUE, NOW(), NOW() FROM tenants T WHERE T.CODE = 'bob-personal';

-- ---- 收入子分類 ----
INSERT INTO categories (TENANT_ID, PARENT_ID, NAME, TYPE, ICON_NAME, COLOR_HEX, IS_SYSTEM_DEFAULT, SOURCE_TEMPLATE_ID, SORT_ORDER, IS_ACTIVE, CREATED_AT, UPDATED_AT)
SELECT T.ID, C.ID, '月薪', 'INCOME', NULL, NULL, TRUE, NULL, 1, TRUE, NOW(), NOW()
FROM tenants T JOIN categories C ON C.TENANT_ID = T.ID AND C.NAME = '薪資收入' AND C.TYPE = 'INCOME'
WHERE T.CODE = 'bob-personal';
INSERT INTO categories (TENANT_ID, PARENT_ID, NAME, TYPE, ICON_NAME, COLOR_HEX, IS_SYSTEM_DEFAULT, SOURCE_TEMPLATE_ID, SORT_ORDER, IS_ACTIVE, CREATED_AT, UPDATED_AT)
SELECT T.ID, C.ID, '獎金', 'INCOME', NULL, NULL, TRUE, NULL, 2, TRUE, NOW(), NOW()
FROM tenants T JOIN categories C ON C.TENANT_ID = T.ID AND C.NAME = '薪資收入' AND C.TYPE = 'INCOME'
WHERE T.CODE = 'bob-personal';
INSERT INTO categories (TENANT_ID, PARENT_ID, NAME, TYPE, ICON_NAME, COLOR_HEX, IS_SYSTEM_DEFAULT, SOURCE_TEMPLATE_ID, SORT_ORDER, IS_ACTIVE, CREATED_AT, UPDATED_AT)
SELECT T.ID, C.ID, '股利', 'INCOME', NULL, NULL, TRUE, NULL, 1, TRUE, NOW(), NOW()
FROM tenants T JOIN categories C ON C.TENANT_ID = T.ID AND C.NAME = '投資收益' AND C.TYPE = 'INCOME'
WHERE T.CODE = 'bob-personal';

-- ---- 支出頂層 ----
INSERT INTO categories (TENANT_ID, PARENT_ID, NAME, TYPE, ICON_NAME, COLOR_HEX, IS_SYSTEM_DEFAULT, SOURCE_TEMPLATE_ID, SORT_ORDER, IS_ACTIVE, CREATED_AT, UPDATED_AT)
SELECT T.ID, NULL, '飲食',     'EXPENSE', 'restaurant',   '#F44336', TRUE, NULL, 1,  TRUE, NOW(), NOW() FROM tenants T WHERE T.CODE = 'bob-personal';
INSERT INTO categories (TENANT_ID, PARENT_ID, NAME, TYPE, ICON_NAME, COLOR_HEX, IS_SYSTEM_DEFAULT, SOURCE_TEMPLATE_ID, SORT_ORDER, IS_ACTIVE, CREATED_AT, UPDATED_AT)
SELECT T.ID, NULL, '交通',     'EXPENSE', 'car',          '#FF9800', TRUE, NULL, 2,  TRUE, NOW(), NOW() FROM tenants T WHERE T.CODE = 'bob-personal';
INSERT INTO categories (TENANT_ID, PARENT_ID, NAME, TYPE, ICON_NAME, COLOR_HEX, IS_SYSTEM_DEFAULT, SOURCE_TEMPLATE_ID, SORT_ORDER, IS_ACTIVE, CREATED_AT, UPDATED_AT)
SELECT T.ID, NULL, '居家生活', 'EXPENSE', 'home',         '#795548', TRUE, NULL, 3,  TRUE, NOW(), NOW() FROM tenants T WHERE T.CODE = 'bob-personal';
INSERT INTO categories (TENANT_ID, PARENT_ID, NAME, TYPE, ICON_NAME, COLOR_HEX, IS_SYSTEM_DEFAULT, SOURCE_TEMPLATE_ID, SORT_ORDER, IS_ACTIVE, CREATED_AT, UPDATED_AT)
SELECT T.ID, NULL, '娛樂',     'EXPENSE', 'game-pad',     '#E91E63', TRUE, NULL, 4,  TRUE, NOW(), NOW() FROM tenants T WHERE T.CODE = 'bob-personal';
INSERT INTO categories (TENANT_ID, PARENT_ID, NAME, TYPE, ICON_NAME, COLOR_HEX, IS_SYSTEM_DEFAULT, SOURCE_TEMPLATE_ID, SORT_ORDER, IS_ACTIVE, CREATED_AT, UPDATED_AT)
SELECT T.ID, NULL, '醫療健康', 'EXPENSE', 'health',       '#00BCD4', TRUE, NULL, 5,  TRUE, NOW(), NOW() FROM tenants T WHERE T.CODE = 'bob-personal';
INSERT INTO categories (TENANT_ID, PARENT_ID, NAME, TYPE, ICON_NAME, COLOR_HEX, IS_SYSTEM_DEFAULT, SOURCE_TEMPLATE_ID, SORT_ORDER, IS_ACTIVE, CREATED_AT, UPDATED_AT)
SELECT T.ID, NULL, '其他支出', 'EXPENSE', 'more-horiz',   '#9E9E9E', TRUE, NULL, 99, TRUE, NOW(), NOW() FROM tenants T WHERE T.CODE = 'bob-personal';

-- ---- 支出子分類 ----
INSERT INTO categories (TENANT_ID, PARENT_ID, NAME, TYPE, ICON_NAME, COLOR_HEX, IS_SYSTEM_DEFAULT, SOURCE_TEMPLATE_ID, SORT_ORDER, IS_ACTIVE, CREATED_AT, UPDATED_AT)
SELECT T.ID, C.ID, '早餐', 'EXPENSE', NULL, NULL, TRUE, NULL, 1, TRUE, NOW(), NOW()
FROM tenants T JOIN categories C ON C.TENANT_ID = T.ID AND C.NAME = '飲食' AND C.TYPE = 'EXPENSE'
WHERE T.CODE = 'bob-personal';
INSERT INTO categories (TENANT_ID, PARENT_ID, NAME, TYPE, ICON_NAME, COLOR_HEX, IS_SYSTEM_DEFAULT, SOURCE_TEMPLATE_ID, SORT_ORDER, IS_ACTIVE, CREATED_AT, UPDATED_AT)
SELECT T.ID, C.ID, '午餐', 'EXPENSE', NULL, NULL, TRUE, NULL, 2, TRUE, NOW(), NOW()
FROM tenants T JOIN categories C ON C.TENANT_ID = T.ID AND C.NAME = '飲食' AND C.TYPE = 'EXPENSE'
WHERE T.CODE = 'bob-personal';
INSERT INTO categories (TENANT_ID, PARENT_ID, NAME, TYPE, ICON_NAME, COLOR_HEX, IS_SYSTEM_DEFAULT, SOURCE_TEMPLATE_ID, SORT_ORDER, IS_ACTIVE, CREATED_AT, UPDATED_AT)
SELECT T.ID, C.ID, '晚餐', 'EXPENSE', NULL, NULL, TRUE, NULL, 3, TRUE, NOW(), NOW()
FROM tenants T JOIN categories C ON C.TENANT_ID = T.ID AND C.NAME = '飲食' AND C.TYPE = 'EXPENSE'
WHERE T.CODE = 'bob-personal';
INSERT INTO categories (TENANT_ID, PARENT_ID, NAME, TYPE, ICON_NAME, COLOR_HEX, IS_SYSTEM_DEFAULT, SOURCE_TEMPLATE_ID, SORT_ORDER, IS_ACTIVE, CREATED_AT, UPDATED_AT)
SELECT T.ID, C.ID, '飲料', 'EXPENSE', NULL, NULL, TRUE, NULL, 4, TRUE, NOW(), NOW()
FROM tenants T JOIN categories C ON C.TENANT_ID = T.ID AND C.NAME = '飲食' AND C.TYPE = 'EXPENSE'
WHERE T.CODE = 'bob-personal';
INSERT INTO categories (TENANT_ID, PARENT_ID, NAME, TYPE, ICON_NAME, COLOR_HEX, IS_SYSTEM_DEFAULT, SOURCE_TEMPLATE_ID, SORT_ORDER, IS_ACTIVE, CREATED_AT, UPDATED_AT)
SELECT T.ID, C.ID, '捷運/公車', 'EXPENSE', NULL, NULL, TRUE, NULL, 1, TRUE, NOW(), NOW()
FROM tenants T JOIN categories C ON C.TENANT_ID = T.ID AND C.NAME = '交通' AND C.TYPE = 'EXPENSE'
WHERE T.CODE = 'bob-personal';
INSERT INTO categories (TENANT_ID, PARENT_ID, NAME, TYPE, ICON_NAME, COLOR_HEX, IS_SYSTEM_DEFAULT, SOURCE_TEMPLATE_ID, SORT_ORDER, IS_ACTIVE, CREATED_AT, UPDATED_AT)
SELECT T.ID, C.ID, '計程車/Uber', 'EXPENSE', NULL, NULL, TRUE, NULL, 2, TRUE, NOW(), NOW()
FROM tenants T JOIN categories C ON C.TENANT_ID = T.ID AND C.NAME = '交通' AND C.TYPE = 'EXPENSE'
WHERE T.CODE = 'bob-personal';
INSERT INTO categories (TENANT_ID, PARENT_ID, NAME, TYPE, ICON_NAME, COLOR_HEX, IS_SYSTEM_DEFAULT, SOURCE_TEMPLATE_ID, SORT_ORDER, IS_ACTIVE, CREATED_AT, UPDATED_AT)
SELECT T.ID, C.ID, '房租', 'EXPENSE', NULL, NULL, TRUE, NULL, 1, TRUE, NOW(), NOW()
FROM tenants T JOIN categories C ON C.TENANT_ID = T.ID AND C.NAME = '居家生活' AND C.TYPE = 'EXPENSE'
WHERE T.CODE = 'bob-personal';
INSERT INTO categories (TENANT_ID, PARENT_ID, NAME, TYPE, ICON_NAME, COLOR_HEX, IS_SYSTEM_DEFAULT, SOURCE_TEMPLATE_ID, SORT_ORDER, IS_ACTIVE, CREATED_AT, UPDATED_AT)
SELECT T.ID, C.ID, '水電費', 'EXPENSE', NULL, NULL, TRUE, NULL, 2, TRUE, NOW(), NOW()
FROM tenants T JOIN categories C ON C.TENANT_ID = T.ID AND C.NAME = '居家生活' AND C.TYPE = 'EXPENSE'
WHERE T.CODE = 'bob-personal';

SET FOREIGN_KEY_CHECKS = 1;
