spring.application.name=NovaLedger
server.port=8111

# === \u6307\u5B9A\u76EE\u524D\u74B0\u5883 ===
#spring.profiles.active=test

# === MySQL \u8CC7\u6599\u5EAB\u8A2D\u5B9A ===
spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:3306/fin_core?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Taipei&characterEncoding=utf8
#spring.datasource.url=jdbc:mysql://localhost:3306/fin_core?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Taipei&characterEncoding=utf8
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# === JPA \u8A2D\u5B9A\uFF08\u95DC\u9375\uFF01\u8B93 Flyway \u8CA0\u8CAC schema \u7BA1\u7406\uFF09===
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false

# === \u65E5\u8A8C\u8A2D\u5B9A ===
logging.level.org.flywaydb=DEBUG
logging.level.org.springframework.boot.autoconfigure.flyway=DEBUG

# === Multipart \u8A2D\u5B9A ===
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

# === JWT \u8A2D\u5B9A ===
#JWT \u7C3D\u7AE0\u7528\u7684\u5BC6\u9470\uFF0C\u7528\u4F86\u7522\u751F\u8207\u9A57\u8B49 token \u7684\u5408\u6CD5\u6027\u3002\u4EFB\u4F55\u4EBA\u62FF\u5230\u9019\u500B\u503C\u5C31\u80FD\u507D\u9020 token\uFF0C\u6240\u4EE5\u6B63\u5F0F\u74B0\u5883\u5FC5\u9808\u6539\u6210\u74B0\u5883\u8B8A\u6578\u6CE8\u5165\uFF0C\u4E0D\u80FD\u5BEB\u6B7B\u5728\u6A94\u6848\u88E1\u3002
jwt.secret=R7!kQ9$Z2f@M6P#A8XWmT%hE4L^cJdVYB3S0n&U5aK

#Access token \u6709\u6548\u671F\uFF0C\u55AE\u4F4D\u6BEB\u79D2\uFF0C3600000 = 1 \u5C0F\u6642\u3002\u904E\u671F\u5F8C\u9700\u8981\u7528 refresh token \u63DB\u65B0\u7684\u3002
jwt.expiration=3600000

#Refresh token \u6709\u6548\u671F\uFF0C604800000 = 7 \u5929\u3002\u7528\u4F86\u63DB\u767C\u65B0\u7684 access token\uFF0C\u6709\u6548\u671F\u6BD4 access token \u9577\u5F88\u591A\uFF0C\u907A\u5931\u98A8\u96AA\u76F8\u5C0D\u9AD8\uFF0C\u5F8C\u7E8C\u53EF\u8003\u616E\u642D\u914D Redis \u505A revoke\u3002
jwt.refresh-expiration=604800000


# === Redis \u8A2D\u5B9A ===
#spring.redis.host=localhost
#spring.redis.port=6379
#spring.redis.timeout=2000
#spring.redis.database=0

# === Swagger / OpenAPI ===
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.enabled=true

# === Auth \u884C\u70BA\u63A7\u5236\uFF08\u6B63\u5F0F\uFF09===
app.auth.skip-email-verify=false

# \u6B63\u5F0F\u74B0\u5883\uFF1Atoken 15 \u5206\u9418
app.auth.verify-token-expire-minutes=15

# resend \u9A57\u8B49\u4FE1\u51B7\u537B\u79D2\u6578\uFF08\u6B63\u5F0F\u74B0\u5883\uFF09
app.auth.resend-cooldown-seconds=60